version: '3.8'
services:
  todo-application:
    container_name: todo-application-1
    image: abdul5798/todo-application:latest
    ports:
      - "8082:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - todo-network

  mysql-db:
    container_name: mysql-db-1
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    networks:
      - todo-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge


